name: Windows Build

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build AirLib
        shell: cmd
        run: build.cmd
