name: Ubuntu Build

# Controls when the action will run.
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        run: ./setup.sh

      - name: Build AirLib
        run: ./build.sh

      - name: Build ROS Wrapper
        run: |
          ./tools/install_ros_deps.sh
          source /opt/ros/*/setup.bash
          cd ros
          catkin build -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8
      
      - name: Build ROS2 Wrapper
        if: matrix.os == 'ubuntu-20.04'
        run: |
          chmod +x ./tools/install_ros2_deps.sh
          ./tools/install_ros2_deps.sh
          source /opt/ros/*/setup.bash
          cd ros2
          colcon build --cmake-args -DCMAKE_C_COMPILER=gcc-8 --cmake-args -DCMAKE_CXX_COMPILER=g++-8

      # Removing support for GazeboDrone. Gazebo is dead. Long live AirSim/Colosseum.
      # - name: Build GazeboDrone
      #   run: |
      #     sudo apt-get install -qq libgazebo9-dev gcc-12 g++-12
      #     ./clean.sh && ./build.sh --gcc
      #     cd GazeboDrone
      #     mkdir build && cd build
      #     cmake -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 ..
      #     make
